### PR TITLE
Updates the naming of the EVR View Inspect tab "EVR View Levels Confi…

### LINKED ISSUE #67: EVR Level Configuration tab should be renamed for clarity
https://jira.jpl.nasa.gov/browse/OMM-175

**Describe the defect**
Tab should be renamed to clarify that it's the EVR Level Style that is being applied, not the EVR level in the view.

Customers unfamiliar with OMM will assume that this tab removes EVR levels from the view, especially with this naming. During demo with mission customer an EVR tab labeled 'Warning EVRs' actually just had all the styles unselected and the customer assumed it was a bug that non-warning EVRs were in the table. 

EVR levels are filtered at query-level by dragging individual levels, modules, or EVR names into the tables. 

**Expected behavior**
The tab functionality should be clearly implied by the tab name.

**Steps To Reproduce**
1. Visual confirmation of tab name 

**Environment (please complete the following information):**
 - Version []
 - Browser []

**Additional context**
Add any other context, code snippets, error messages, screen shots about the problem here.

|Criticality|Name|Description|
|---|---|---|
|crit1|Critical|Defect makes the software unusable for mission operations.|
|crit2|Major|Defect has significant impact on usability of delivered software for mission operations. User experience is difficult and/or cumbersome. Workaround available is arduous.|
|crit3|Moderate|Defect has moderate to mild impact on usability of delivered software for mission operations. User experience is degraded but workable.|
|crit4|Minor|Defect means software does not work as originally intended, but the defect has little impact on the usability of the delivered software.|

### PR DESCRIPTION
**Pull request by mudinthewater**
Closes #67

### CODE REVIEW

**Comment by mudinthewater** [comment]
Since there is already a style tab, I updated it instead to 'Color' as that's more in line with what we're technically doing here. The color options come from config.js and truly are individual colors as opposed to styles.

**Review by davetsay — CHANGES_REQUESTED** [review]
This is a great change. Can you shorten it to `Level Color` or just `Color`? There is going to be more tab name changes coming soon and tabs like `EVR View Configuration` will be shortened to just `Config`.

**Comment by mudinthewater** [comment]
Sure, I'll update it next week.

**Review by davetsay — APPROVED** [review]
Thanks for the contribution @mudinthewater

**Pull request merged**
